setting:
  request: # 网络请求设置
    timeout: 10 # 超时设置
    ssl: false # ssl设置

  gitee_friends_links: # gitee友链配置
    enable: false
    owner:
    repo:
    state: open
    labelid:  # none关闭功能

  github_friends_links: # github友链配置
    enable: true
    owner: cayzlh
    repo: studious-spork
    state: open
    label: active # none关闭功能
